# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-30 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.TextField(max_length=100, unique=True)),
                ('name', models.TextField(default=' ', max_length=100)),
                ('public_key', models.TextField(blank=True, default=' ', max_length=500)),
                ('private_key', models.TextField(blank=True, default=' ', max_length=500)),
                ('age', models.IntegerField(default=18)),
                ('description', models.TextField(blank=True, default=' ', max_length=500)),
                ('is_manage', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
